# Setup
title:               Uooh's blog
tagline:             ''
url:                 'https://sowoibu.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty
google_site_verification : DEfAPAlWoNGCY0FXF1I34YjjqJFlyUhl9WH9nQ7TQ1A



# About/contact


# Gems
plugins:
  - jekyll-paginate

# Custom vars
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Social Info
navigation: False


